version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2022.05
    steps:
      - run: echo "hello world"
  build2:
    docker:
      - image: cimg/base:2022.05
    steps:
      - run: echo "hello world 222"

workflows:
  build1AndBuild2:
    jobs:
      - build
      - build2:
          requires:
            - build
