version: 2.1

executors:
  vm:
    machine:
      image: ubuntu-2004:2024.01.2
      docker_layer_caching: true

jobs:
  test:
    <<: &defaults
    executor: vm
    steps:
      - run:
          name: Run lint checks
          command: make test

  build:
    executor: vm
    steps:
      - run:
          name: Build the project
          command: make build

workflows:
  build1AndBuild2:
    jobs:
      - test
      - build:
          requires:
            - test
