version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2022.05
    steps:
      - run: echo "hello world"
  test:
    docker:
      - image: cimg/base:2022.05
    steps:
      - run: make test

workflows:
  build1AndBuild2:
    jobs:
      - test
      - build:
          requires:
            - test
